Planner24/24planner.zip

BE/build.gradle, BE/compose.yaml, BE/src/main/java/com/example/p24zip/P24zipApplication.java, BE/src/main/resources/application.properties, FE/.prettierrc, FE/package-lock.json, FE/package.json
- P24-11
- DB 도커에 생성되도록 수정
- 백엔드 프로젝트 실행 시 자동으로 DB 컨테이너 실행되도록 설정
- prettier 설정
- @EnableJpaAuditing 추가
npm install 해주세요~
dependencies도 추가되었습니다.
=> [P24-11] chore: DB 도커 세팅 및 prettier 설정

BE/src/main/java/com/example/p24zip/domain/user/dto/request/SignupRequestDto.java, BE/src/main/java/com/example/p24zip/domain/user/service/AuthService.java, BE/src/main/java/com/example/p24zip/global/exception/GlobalExceptionHandler.java
- P24-20
- 이메일 형식이 안맞을 때 예외 처리
- 비밀번호 형식이 안맞을 때 예외 처리
- 닉네임 형식이 안맞을 때 예외 처리
- GlobaExceptionHandler 변경 사항 있음
=> [P24-20] feat: [BE] 회원가입 입력 값 예외 처리

BE/src/main/java/com/example/p24zip/domain/user/controller/AuthController.java, BE/src/main/java/com/example/p24zip/domain/user/service/AuthService.java
- [P24-25] fix: [BE] redis key 수정
[P24-25]: https://j9603h.atlassian.net/browse/P24-25?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [P24-25] fix: [BE] redis key 수정

BE/src/main/java/com/example/p24zip/domain/user/controller/AuthController.java, BE/src/main/java/com/example/p24zip/domain/user/dto/request/VerifyEmailRequestCodeDto.java, BE/src/main/java/com/example/p24zip/domain/user/dto/response/AccessTokenResponseDto.java, BE/src/main/java/com/example/p24zip/domain/user/dto/response/LoginResponseDto.java, BE/src/main/java/com/example/p24zip/domain/user/service/AuthService.java, BE/src/main/java/com/example/p24zip/global/exception/GlobalExceptionHandler.java, BE/src/main/java/com/example/p24zip/global/security/handler/JwtAuthenticationEntryPoint.java
- P24-26
- 이메일 인증 확인 구현
- 토큰 관련하여 t -> T로 변경
- 회원가입 버튼 클릭 시 중복 닉네임 예외 처리
- 닉네임 중복 확인 시 닉네임 형식 올바르지 않을 때 예외 처리
=> [P24-26] feat: [BE] 이메일 인증 확인 구현 완료

BE/src/main/java/com/example/p24zip/domain/user/service/AuthService.java
- [P24-27] fix: [BE] logout exception 수정
[P24-27]: https://j9603h.atlassian.net/browse/P24-27?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [P24-27] fix: [BE] logout exception 수정

BE/compose.yaml, FE/Dockerfile, FE/nginx.conf, FE/package-lock.json, FE/package.json, FE/vite.config.js
- [p24-39] chore: [DP] 1차 자동화 배포
=> [p24-39] chore: [DP] 1차 자동화 배포

.github/workflows/deploy.yml
- [P24-41] fix: [DP] deploy.yml 수정
[P24-41]: https://j9603h.atlassian.net/browse/P24-41?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [P24-41] fix: [DP] deploy.yml 수정

.github/workflows/deploy.yml
- [P24-41] [DP] deploy.yml 수정
[P24-41]: https://j9603h.atlassian.net/browse/P24-41?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [P24-41] [DP] deploy.yml 수정

FE/src/pages/Login.jsx
- P24-38
- 로그인 페이지에서 회원가입 요청 부분 간격 조절
=> [P24-38] style: 로그인 CSS 수정

BE/src/main/java/com/example/p24zip/domain/user/controller/AuthController.java, BE/src/main/java/com/example/p24zip/domain/user/service/AuthService.java
- P24-35
- 이메일 인증 요청을 5초안에 연속적으로 다시 요청 할 경우 예외 처리
=> [P24-35] feat: [BE] 이메일 인증 요청 추가 예외 처리

.github/workflows/deploy.yml, BE/src/main/java/com/example/p24zip/global/config/SecurityConfig.java, BE/src/main/resources/application.properties
- [P24-47] fix: [DP] 배포 수정
[P24-47]: https://j9603h.atlassian.net/browse/P24-47?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [P24-47] fix: [DP] 배포 수정

BE/src/main/java/com/example/p24zip/domain/movingPlan/entity/MovingPlan.java
- 다른 Entity와 연관되어있어서 일단 먼저 생성
- P24-46
=> [P24-46] feat: [BE] 이사 플랜 Entity 생성

.github/workflows/deploy.yml, BE/src/main/java/com/example/p24zip/domain/user/dto/response/VerifyEmailDataResponseDto.java, BE/src/main/java/com/example/p24zip/domain/user/service/AuthService.java, BE/src/main/resources/application.properties, FE/src/pages/Signup.jsx
- P24-44
- 배포 환경에서 이메일 인증코드 만료까지 남은 시간이 정상적으로 작동하지 않는 문제 발생
- 백엔드에서 만료시간을 전달할 때 시간대를 명시하도록 수정
- 시간대를 명시하면 브라우저 지역과 상관없이 브라우저에서 시간대 정보를 인식하고 처리한다고 합니다.
=> [P24-44] fix: [FE] 회원가입 이메일 인증 남은 시간 오류 해결

BE/src/main/java/com/example/p24zip/domain/movingPlan/repository/MovingPlanRepository.java
- P24-49
- Repository가 있어야 사용하는데 아까 Entity만 만들었습니다..
=> [P24-49] feat: [BE] 이사 플랜 Repository 생성

BE/src/main/java/com/example/p24zip/domain/task/entity/Task.java, BE/src/main/java/com/example/p24zip/domain/task/repository/TaskRepository.java, BE/src/main/java/com/example/p24zip/domain/taskGroup/entity/TaskGroup.java, BE/src/main/java/com/example/p24zip/domain/taskGroup/repository/TaskGroupRepository.java
- P24-53
- 체크그룹, 체크포인트 API 구현을 위한 기본 세팅 함께 진행
=> [P24-53] feat: [BE] 체크그룹, 체크포인트 Entity 및 Repository 생성

FE/src/api/mapApi.js, FE/src/component/map/Map.jsx, FE/src/component/map/MapModal.jsx
- [P24-61]  feat: [FE] 지도  페이지 완성
[P24-61]: https://j9603h.atlassian.net/browse/P24-61?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [P24-61]  feat: [FE] 지도  페이지 완성

FE/src/component/map/Map.jsx, FE/src/component/map/MapModal.jsx
- [P24-65] fix: [FE] 지도 페이지 버튼 클릭 수정
[P24-65]: https://j9603h.atlassian.net/browse/P24-65?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [P24-65] fix: [FE] 지도 페이지 버튼 클릭 수정

BE/src/main/java/com/example/p24zip/domain/house/controller/HouseController.java, BE/src/main/java/com/example/p24zip/domain/house/service/HouseService.java
- P24-67
- 해당 이사계획에 속하지 않은 집에 대해서 처리하려 할 때 예외 처리
=> [P24-67] feat: [BE] 집 관련 예외처리 추가

BE/src/main/java/com/example/p24zip/domain/house/controller/HouseController.java, BE/src/main/java/com/example/p24zip/domain/house/dto/request/AddHouseRequestDto.java, BE/src/main/java/com/example/p24zip/domain/house/dto/request/ChangeHouseDetailAddressRequestDto.java, BE/src/main/java/com/example/p24zip/domain/house/dto/response/ChangeHouseDetailAddressResponseDto.java, BE/src/main/java/com/example/p24zip/domain/house/entity/House.java, BE/src/main/java/com/example/p24zip/domain/house/service/HouseService.java
- 상세주소 최대 35글자까지로 제한
- P24-71
- 상세주소 최대 35글자까지로 제한
- 집 상세주소 수정 기능 구현
=> [P24-71] feat: [BE] 집 상세주소 수정 구현 완료

BE/src/main/java/com/example/p24zip/domain/house/service/HouseService.java
- P24-72
- HouseService의 isMovingPlanIdMatched 메서드 로직 수정
=> [P24-72] fix: 예외 처리 메서드 로직 수정

FE/src/api/mapApi.js, FE/src/component/map/Map.jsx, FE/src/component/map/MapModal.jsx, FE/src/component/map/MapSidebar.jsx, FE/src/pages/Houses.jsx
- [P24-66] feat: [FE] 지도 페이지 보완 및 지도 세부 페이지 완성
[P24-66]: https://j9603h.atlassian.net/browse/P24-66?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [P24-66] feat: [FE] 지도 페이지 보완 및 지도 세부 페이지 완성

FE/src/component/map/MapModal.jsx, FE/src/component/map/MapSidebar.jsx, FE/src/layout/RootLayout.jsx
- [P24-75] fix: [FE] 집 삭제 및 수정 재구성
[P24-75]: https://j9603h.atlassian.net/browse/P24-75?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [P24-75] fix: [FE] 집 삭제 및 수정 재구성

FE/src/component/map/Map.jsx
- [P24-76] fix: [FE] 지도 페이지 수정 및 에러 페이지 이동
[P24-76]: https://j9603h.atlassian.net/browse/P24-76?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [P24-76] fix: [FE] 지도 페이지 수정 및 에러 페이지 이동

FE/src/component/map/MapModal.jsx
- [P24-78] fix: [FE] 지도 중복 생성 에러 수정
[P24-78]: https://j9603h.atlassian.net/browse/P24-78?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [P24-78] fix: [FE] 지도 중복 생성 에러 수정

FE/src/component/map/Map.jsx, FE/src/component/map/MapModal.jsx, FE/src/component/map/MapSidebar.jsx
- [P24-80] fix: [FE] 지도 상세페이지 수정 버튼 엔터 수정
[P24-80]: https://j9603h.atlassian.net/browse/P24-80?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [P24-80] fix: [FE] 지도 상세페이지 수정 버튼 엔터 수정

BE/src/main/java/com/example/p24zip/domain/movingPlan/controller/MovingPlanController.java, BE/src/main/java/com/example/p24zip/domain/movingPlan/entity/MovingPlan.java, BE/src/main/java/com/example/p24zip/domain/movingPlan/service/MovingPlanService.java, FE/src/api/planApi.js, FE/src/component/plan/Plan.jsx, FE/src/component/plan/PlanCreator.jsx, FE/src/pages/PlanList.jsx, FE/src/pages/PlanSetting.jsx
- P24-77
- 이사 플랜 페이지 디자인 보완
- 플랜 조회 api 구현 및 플랜 삭제 api 보완
- 이사 플랜 제목 수정 기능 구현
- 이사 플랜 삭제 기능 구현 (confirm 창을 통해 확인 후 삭제)
=> [P24-77] feat: [FE] 이사 플랜 설정 페이지 구현

BE/src/main/java/com/example/p24zip/domain/task/dto/response/TaskListResponseDto.java, BE/src/main/java/com/example/p24zip/domain/task/service/TaskService.java, BE/src/main/java/com/example/p24zip/domain/taskGroup/dto/request/TaskGroupRequestDto.java, BE/src/main/java/com/example/p24zip/domain/taskGroup/dto/response/TaskGroupMemoUpdateResponseDto.java, BE/src/main/java/com/example/p24zip/domain/taskGroup/entity/TaskGroup.java, FE/src/api/taskApi.js, FE/src/api/taskGroupApi.js, FE/src/component/taskList/Task.jsx, FE/src/component/taskList/TaskGroupInfo.jsx, FE/src/component/taskList/TaskGroupMemo.jsx, FE/src/component/taskList/TaskListSection.jsx, FE/src/layout/RootLayout.jsx, FE/src/pages/TaskList.jsx
- P24-68
- 체크 그룹 제목 수정 기능 구현
- 체크 그룹 메모 수정 기능 구현
- 체크 그룹 삭제 기능 구현
- 체크포인트 생성 기능 구현
- 체크포인트 리스트 조회 기능 구현
- 체크포인트 내용 수정 기능 구현
- 체크포인트 완료여부 수정 기능 구현
- 체크포인트 삭제 기능 구현
=> [P24-68] feat: [FE] 체크포인트 페이지 구현

FE/src/api/taskGroupApi.js, FE/src/component/TaskGroup/TaskGroupBox.jsx
- P24-82
- taskGroupApi 오류 해결 및 체크 그룹 navigate 추가
=> [P24-82] fix: [FE] taskGroupApi 오류 해결 및 체크 그룹 navigate 추가

FE/src/component/map/Map.jsx, FE/src/component/map/MapModal.jsx
- [P24-86] fix: [FE] 지도 메인 페이지 및 상세 페이지 보완 및 완성
[P24-86]: https://j9603h.atlassian.net/browse/P24-86?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [P24-86] fix: [FE] 지도 메인 페이지 및 상세 페이지 보완 및 완성

BE/src/main/java/com/example/p24zip/domain/schedule/dto/request/ScheduleRequestDto.java, BE/src/main/java/com/example/p24zip/domain/schedule/entity/Schedule.java, BE/src/main/java/com/example/p24zip/domain/task/dto/request/TaskRequestDto.java, BE/src/main/java/com/example/p24zip/domain/task/entity/Task.java, BE/src/main/java/com/example/p24zip/domain/taskGroup/dto/request/TaskGroupMemoUpdateRequestDto.java, FE/src/component/taskList/Task.jsx, FE/src/component/taskList/TaskListSection.jsx
- P24-85
- 체크 그룹 메모, 체크포인트 내용, 캘린더 할 일 글자수 제한
- 내용 없이 체크포인트 생성 시 '체크포인트 추가하기'로 돌아가는 로직 추가
- 완료된 체크포인트 삭제 시 완료된 체크포인트 카운팅 오류 해결
=> [P24-85] fix: [FE] 체크포인트 보완

FE/src/pages/Login.jsx, FE/src/pages/Signup.jsx
- P24-87
- 로그인 상태로 로그인, 회원가입 페이지 접근 시 메인 페이지로 이동
=> [P24-87] feat: [FE] 로그인 상태로 로그인, 회원가입 페이지 접근 제한

BE/src/main/java/com/example/p24zip/domain/movingPlan/dto/request/MovingPlanRequestDto.java, BE/src/main/java/com/example/p24zip/domain/movingPlan/entity/MovingPlan.java, FE/src/component/plan/Plan.jsx, FE/src/component/plan/PlanCreator.jsx
- P24-88
- 이사 플랜 제목 최대 글자 수 설정
- 플랜 추가 버튼 빠르게 여러번 클릭하면 플랜이 여러개 생성되는 문제 해결
- 플랜 목록에서 각 플랜에 대핸 설정 버튼 클릭되는 영역 확대
=> [P24-88] fix: [FE] 이사 플랜 관련 보완

BE/src/main/java/com/example/p24zip/domain/house/entity/House.java, FE/src/component/TaskGroup/TaskGroupBox.jsx, FE/src/pages/TaskGroups.jsx
- P24-84
- style: 마우스 커서 설정
- style: input 입력 시 outline 제거
- 체크 그룹 생성 확장성 있게 refactor
- 체크 그룹 박스를 눌러서 토글되는 방식 -> 입력창 뜨는 방식은 박스를 눌러서, 다시 + 박스로 돌아가는 방식은 x를 눌러서 토글되는 방식
- 체크 그룹 생성 시 여러 번 요청 되는 것 막는 예외 처리
=> [P24-84] feat: [FE] 체크 그룹 보완 사항

FE/src/api/axios.js
- P24-91
- 브라우저 창 닫은 후 액세스 토큰 미삭제 오류 해결
=> [P24-91] fix:  [FE] 브라우저 창 닫은 후 액세스 토큰 미삭제 오류 해결

FE/src/component/plan/PlanCreator.jsx, FE/src/pages/PlanSetting.jsx
- P24-93
- 이사 플랜 제목 수정 관련 설정 페이지 보완
- 최대 글자 수에 맞춰 input 영역 수정
- 생성과 관련된 요소들 색상 다른 페이지와 통일
- 플랜 설정 페이지에서 제목 수정 시, 헤더에 바로 반영되도록 보완
=> [P24-93] feat: [FE] 이사 플랜 관련 추가 보완 

FE/src/component/TaskGroup/TaskGroupBox.jsx, FE/src/component/map/Map.jsx, FE/src/pages/TaskGroups.jsx
- P24-92
- 살 곳 정하기 페이지 화면에 제목 지우기
- 체크 그룹 관련 CSS 변경
- 다른 사용자의 체크 그룹에 접근할 때 예외 처리
=> [P24-92] style: [FE] 살 곳 정하기 및 체크 그룹 페이지 CSS 변경

BE/src/main/java/com/example/p24zip/domain/chat/controller/ChatController.java, BE/src/main/java/com/example/p24zip/domain/chat/service/ChatService.java, BE/src/main/java/com/example/p24zip/domain/user/service/AuthService.java, FE/src/pages/Chat.jsx
- P24-99 fix: [BE/FE] 실시간 구현 수정
=> P24-99 fix: [BE/FE] 실시간 구현 수정

FE/src/component/TaskGroup/TaskGroupBox.jsx, FE/src/pages/TaskGroups.jsx, FE/src/store/store.js
=> [P24-101] fix: 배포 오류 해결

FE/src/pages/NewPassword.jsx, FE/src/router/index.jsx
=> [P24-102] fix: 배포 에러 해결2

BE/src/main/java/com/example/p24zip/domain/user/dto/response/VerifyEmailDataResponseDto.java, BE/src/main/java/com/example/p24zip/domain/user/service/AuthService.java
- P24-102
- 이메일 인증 코드 확인쪽 백엔드 에러 해결
=> [P24-102] fix: [BE] 에러 해결

BE/src/main/java/com/example/p24zip/domain/chat/controller/ChatController.java, BE/src/main/java/com/example/p24zip/domain/chat/dto/response/ChatsErrorResponseDto.java, BE/src/main/java/com/example/p24zip/global/exception/GlobalExceptionHandler.java, BE/src/main/java/com/example/p24zip/global/exception/StompTokenException.java, FE/src/component/map/Map.jsx, FE/src/pages/Chat.jsx
- P24-105 fix: [BE/FE] 실시간 채팅 에러 처리 수정
=> P24-105 fix: [BE/FE] 실시간 채팅 에러 처리 수정

BE/src/main/java/com/example/p24zip/domain/movingPlan/entity/MovingPlan.java, FE/src/component/plan/Plan.jsx
- P24-109
- movingPlan 엔티티에 chat 엔티티에 대한 cascade 삭제 명시
- 이사 목록에서 플랜 주인/동거인 표시되도록 추가
=> [P24-109] fix: [FE/BE] 이사 플랜 보완

FE/src/component/taskList/Task.jsx, FE/src/component/taskList/TaskListSection.jsx
- P24-108
- 체크포인트 엔터키로 저장 시 중복 제출 오류 해결
- 체크포인트 카운팅 오류 해결
=> [P24-108] fix: [FE] 체크포인트 중복 제출 및 카운팅 오류 해결

FE/src/component/map/Map.jsx
- [P24-110] fix: [FE] 지도 현재 위치 수정
[P24-110]: https://j9603h.atlassian.net/browse/P24-110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [P24-110] fix: [FE] 지도 현재 위치 수정

BE/src/main/java/com/example/p24zip/domain/chat/dto/response/MessageResponseDto.java, BE/src/main/java/com/example/p24zip/domain/chat/service/ChatService.java, FE/src/pages/Chat.jsx
- [P24-111] feat: [BE/FE] 실시간 채팅 날짜 추가
[P24-111]: https://j9603h.atlassian.net/browse/P24-111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [P24-111] feat: [BE/FE] 실시간 채팅 날짜 추가

FE/src/pages/Login.jsx
- P24-117
- 로그인 페이지 비밀번호 찾기 버튼 추가
=> [P24-117] feat: [FE] 로그인 페이지 비밀번호 찾기 버튼 추가

BE/src/main/java/com/example/p24zip/domain/chat/repository/ChatRepository.java, BE/src/main/java/com/example/p24zip/domain/movingPlan/repository/HousemateRepository.java, BE/src/main/java/com/example/p24zip/domain/user/controller/UserController.java, BE/src/main/java/com/example/p24zip/domain/user/entity/User.java, BE/src/main/java/com/example/p24zip/domain/user/service/AuthService.java, FE/src/api/userApi.js, FE/src/pages/Mypage.jsx
=> [P24-107] feat: [BE/FE] 회원 탈퇴

FE/src/pages/Mypage.jsx, FE/src/router/index.jsx
- P24-124
- 마이페이지 style 조정 및 errorElement 처리 열기
=> [P24-124] style: [FE] 마이페이지 스타일 및 errorElement 처리

BE/src/main/java/com/example/p24zip/domain/chat/controller/ChatController.java, BE/src/main/java/com/example/p24zip/domain/chat/dto/response/ChatsResponseDto.java
- [P24-125] fix: [BE] 실시간 채팅 변수명 수정
[P24-125]: https://j9603h.atlassian.net/browse/P24-125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [P24-125] fix: [BE] 실시간 채팅 변수명 수정
